import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { Appointment } from '@/types/appointment';

interface AppointmentState {
  appointments: Appointment[];
  addAppointment: (appointment: Omit<Appointment, 'id' | 'createdAt' | 'updatedAt'>) => void;
  updateAppointment: (id: string, appointment: Partial<Appointment>) => void;
  deleteAppointment: (id: string) => void;
  getAppointmentById: (id: string) => Appointment | undefined;
}

const mockAppointments: Appointment[] = [
  {
    id: '1',
    orderNumber: 'OP-2025-001',
    productionOrderId: '1',
    productName: 'Parafuso M8x50',
    productCode: 'PAR-M8-50',
    machine: 'Torno CNC 01',
    operator: 'João Santos',
    shift: 'Manhã',
    date: '2025-01-15',
    startTime: '08:00',
    endTime: '12:00',
    quantityProduced: 1200,
    quantityRejected: 25,
    setupTime: 45,
    productionTime: 195,
    stopTime: 0,
    efficiency: 94.5,
    oee: 89.2,
    availability: 100,
    performance: 92.3,
    quality: 97.9,
    status: 'Concluído',
    notes: 'Produção normal',
    createdAt: '2025-01-15T08:00:00',
    updatedAt: '2025-01-15T12:00:00',
    createdBy: 'João Santos'
  },
  {
    id: '2',
    orderNumber: 'OP-2025-001',
    productionOrderId: '1',
    productName: 'Parafuso M8x50',
    productCode: 'PAR-M8-50',
    machine: 'Torno CNC 01',
    operator: 'João Santos',
    shift: 'Tarde',
    date: '2025-01-15',
    startTime: '13:00',
    endTime: '17:30',
    quantityProduced: 1350,
    quantityRejected: 30,
    setupTime: 0,
    productionTime: 240,
    stopTime: 30,
    stopReason: 'Troca de Ferramenta',
    efficiency: 91.8,
    oee: 84.5,
    availability: 88.9,
    performance: 94.2,
    quality: 97.8,
    status: 'Concluído',
    notes: 'Parada para manutenção preventiva',
    createdAt: '2025-01-15T13:00:00',
    updatedAt: '2025-01-15T17:30:00',
    createdBy: 'João Santos'
  },
  {
    id: '3',
    orderNumber: 'OP-2025-001',
    productionOrderId: '1',
    productName: 'Parafuso M8x50',
    productCode: 'PAR-M8-50',
    machine: 'Torno CNC 01',
    operator: 'Maria Silva',
    shift: 'Noite',
    date: '2025-01-15',
    startTime: '18:00',
    endTime: '22:00',
    quantityProduced: 1100,
    quantityRejected: 15,
    setupTime: 0,
    productionTime: 220,
    stopTime: 20,
    stopReason: 'Reabastecimento',
    efficiency: 93.2,
    oee: 88.7,
    availability: 91.7,
    performance: 95.5,
    quality: 98.6,
    status: 'Concluído',
    createdAt: '2025-01-15T18:00:00',
    updatedAt: '2025-01-15T22:00:00',
    createdBy: 'Maria Silva'
  },
  {
    id: '4',
    orderNumber: 'OP-2025-005',
    productionOrderId: '5',
    productName: 'Engrenagem Z24',
    productCode: 'ENG-Z24',
    machine: 'Fresadora CNC 01',
    operator: 'Ana Lima',
    shift: 'Manhã',
    date: '2025-01-14',
    startTime: '08:00',
    endTime: '12:00',
    quantityProduced: 140,
    quantityRejected: 8,
    setupTime: 90,
    productionTime: 150,
    stopTime: 0,
    efficiency: 85.2,
    oee: 72.5,
    availability: 100,
    performance: 81.1,
    quality: 94.6,
    status: 'Concluído',
    notes: 'Setup demorado - verificar setup sheet',
    createdAt: '2025-01-14T08:00:00',
    updatedAt: '2025-01-14T12:00:00',
    createdBy: 'Ana Lima'
  },
  {
    id: '5',
    orderNumber: 'OP-2025-005',
    productionOrderId: '5',
    productName: 'Engrenagem Z24',
    productCode: 'ENG-Z24',
    machine: 'Fresadora CNC 01',
    operator: 'Ana Lima',
    shift: 'Tarde',
    date: '2025-01-14',
    startTime: '13:00',
    endTime: '15:30',
    quantityProduced: 140,
    quantityRejected: 7,
    setupTime: 0,
    productionTime: 120,
    stopTime: 30,
    stopReason: 'Manutenção',
    efficiency: 78.5,
    oee: 65.3,
    availability: 80.0,
    performance: 85.7,
    quality: 95.2,
    status: 'Pausado',
    notes: 'Manutenção preventiva - retorno previsto 15/01',
    createdAt: '2025-01-14T13:00:00',
    updatedAt: '2025-01-14T15:30:00',
    createdBy: 'Ana Lima'
  },
  {
    id: '6',
    orderNumber: 'OP-2025-002',
    productionOrderId: '2',
    productName: 'Porca Sextavada M8',
    productCode: 'POR-M8',
    machine: 'Prensa Excêntrica 02',
    operator: 'Maria Oliveira',
    shift: 'Manhã',
    date: '2025-01-10',
    startTime: '08:00',
    endTime: '12:00',
    quantityProduced: 3200,
    quantityRejected: 45,
    setupTime: 30,
    productionTime: 210,
    stopTime: 0,
    efficiency: 96.8,
    oee: 93.2,
    availability: 100,
    performance: 97.7,
    quality: 98.6,
    status: 'Concluído',
    createdAt: '2025-01-10T08:00:00',
    updatedAt: '2025-01-10T12:00:00',
    createdBy: 'Maria Oliveira'
  },
  {
    id: '7',
    orderNumber: 'OP-2025-002',
    productionOrderId: '2',
    productName: 'Porca Sextavada M8',
    productCode: 'POR-M8',
    machine: 'Prensa Excêntrica 02',
    operator: 'Maria Oliveira',
    shift: 'Tarde',
    date: '2025-01-10',
    startTime: '13:00',
    endTime: '17:00',
    quantityProduced: 3400,
    quantityRejected: 52,
    setupTime: 0,
    productionTime: 220,
    stopTime: 20,
    stopReason: 'Ajuste de Ferramenta',
    efficiency: 95.5,
    oee: 90.8,
    availability: 91.7,
    performance: 97.3,
    quality: 98.5,
    status: 'Concluído',
    createdAt: '2025-01-10T13:00:00',
    updatedAt: '2025-01-10T17:00:00',
    createdBy: 'Maria Oliveira'
  },
  {
    id: '8',
    orderNumber: 'OP-2025-002',
    productionOrderId: '2',
    productName: 'Porca Sextavada M8',
    productCode: 'POR-M8',
    machine: 'Prensa Excêntrica 02',
    operator: 'Carlos Souza',
    shift: 'Noite',
    date: '2025-01-10',
    startTime: '18:00',
    endTime: '22:00',
    quantityProduced: 3400,
    quantityRejected: 53,
    setupTime: 0,
    productionTime: 220,
    stopTime: 20,
    stopReason: 'Setup Rápido',
    efficiency: 94.2,
    oee: 89.5,
    availability: 91.7,
    performance: 96.4,
    quality: 98.4,
    status: 'Concluído',
    createdAt: '2025-01-10T18:00:00',
    updatedAt: '2025-01-10T22:00:00',
    createdBy: 'Carlos Souza'
  },
  {
    id: '9',
    orderNumber: 'OP-2025-004',
    productionOrderId: '4',
    productName: 'Eixo Transmissão X50',
    productCode: 'EIX-X50',
    machine: 'Torno CNC 02',
    operator: 'Pedro Costa',
    shift: 'Tarde',
    date: '2025-01-15',
    startTime: '16:00',
    endTime: '17:00',
    quantityProduced: 0,
    quantityRejected: 0,
    setupTime: 60,
    productionTime: 0,
    stopTime: 0,
    efficiency: 0,
    oee: 0,
    availability: 100,
    performance: 0,
    quality: 100,
    status: 'Em Andamento',
    notes: 'Setup em andamento',
    createdAt: '2025-01-15T16:00:00',
    updatedAt: '2025-01-15T17:00:00',
    createdBy: 'Pedro Costa'
  },
  {
    id: '10',
    orderNumber: 'OP-2025-001',
    productionOrderId: '1',
    productName: 'Parafuso M8x50',
    productCode: 'PAR-M8-50',
    machine: 'Torno CNC 01',
    operator: 'João Santos',
    shift: 'Manhã',
    date: '2025-01-16',
    startTime: '08:00',
    quantityProduced: 450,
    quantityRejected: 10,
    setupTime: 0,
    productionTime: 90,
    stopTime: 0,
    efficiency: 93.8,
    oee: 89.5,
    availability: 100,
    performance: 94.2,
    quality: 97.8,
    status: 'Em Andamento',
    createdAt: '2025-01-16T08:00:00',
    updatedAt: '2025-01-16T09:30:00',
    createdBy: 'João Santos'
  }
];

export const useAppointmentStore = create<AppointmentState>()(
  persist(
    (set, get) => ({
      appointments: mockAppointments,
      
      addAppointment: (appointmentData) => {
        const newAppointment: Appointment = {
          ...appointmentData,
          id: Date.now().toString(),
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        };
        set((state) => ({ appointments: [...state.appointments, newAppointment] }));
      },
      
      updateAppointment: (id, appointmentData) => {
        set((state) => ({
          appointments: state.appointments.map((appointment) =>
            appointment.id === id
              ? { ...appointment, ...appointmentData, updatedAt: new Date().toISOString() }
              : appointment
          ),
        }));
      },
      
      deleteAppointment: (id) => {
        set((state) => ({
          appointments: state.appointments.filter((appointment) => appointment.id !== id),
        }));
      },
      
      getAppointmentById: (id) => {
        return get().appointments.find((appointment) => appointment.id === id);
      },
    }),
    {
      name: 'appointments-storage',
    }
  )
);
